name: Watchtower
services:
    watchtower:
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        image: containrrr/watchtower
         command: --cleanup --include-restarting --rolling-restart --include-stopped --interval 21600
